### PR TITLE
fix #1221 do not lint diff windows

### LINKED ISSUE #1221: CompareWithSavedAction problems stay in problems window after closing diff page
## Environment data
VS Code version:  1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d)
Python Extension version:  0.7.0
Python Version: '3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)]'
OS and version: Windows 7   

## Actual behavior

When using the CompareWithSavedAction on python files you get a diff between the unsaved file in buffer and the original file on the disk. Their url-scheme starts with 'showModifications:'. Linting problems found by the python extensions will be shown in the problems window for these 'showModifications:'-urls too. But they won't get removed from the problems window, when the diff-tab is closed. The only way I found the get rid of those, is to close and reopen the vscode window.

## Expected  behavior

Either when opening the CompareWithSavedAction-tab the problems 'caused' by this 'file' are not added to the problems window, because those are just duplicates, or when the CompareWithSavedAction-tab is closed those problems are removed too.

## Steps to reproduce:  
- open python file (with linting problems)
- change python file (still having linting problems)
- in explorer view (Ctrl-Shift-E) in the open editors window (left top) right-click on changed file and select 'Compare with saved file' (Ctrl+K D)
- menu 'View' - 'Problems' (Ctrl-Shift-M)
- duplicate problems tree for 'showModifications:<path_to_original_file>'
- close diff tab
- duplicate problems are still in problems view (Ctrl-Shift-M) rendering the problems-counter on the bottom left useless.
-----
- close vscode
- reopen vscode
- duplicate problems are gone

## Logs
Output from ```Python``` output panel  is just the normal linting output.

Output from ```Console window``` (Help->Developer Tools menu):
None

### PR DESCRIPTION
**Pull request by DonJayamanne**

### CODE REVIEW

File: src/client/providers/lintProvider.ts [hunk 1]
```diff
@@ -98,7 +98,7 @@ export class LintProvider extends vscode.Disposable {
                 return;
             }
             // Exclude files opened by vscode when showing a diff view
-            if (e.uri.scheme === 'git') {
+            if (e.uri.scheme === 'git' || e.uri.scheme === 'showModifications') {
```
Comment (brettcannon) [inline src/client/providers/lintProvider.ts]: I assume there's no magical constant defined somewhere that we could use here instead?

Comment (DonJayamanne) [reply src/client/providers/lintProvider.ts]: None that i'm aware of.
But i'll update so it is a little easier to manage.

Comment (DonJayamanne) [reply src/client/providers/lintProvider.ts]: Added a new commit with a constant for the above resources.
