### PR TITLE
fix #1041 when debugging a test do not cancel it when re-discovering tests

### LINKED ISSUE #1041: Debugger hangs
## Environment data
VS Code version:  1.13.1
Python Extension version:  0.6.5
Python Version:  3.5.2 
OS and version:  Ubuntu 16.04 LTS (running as a virtual machine in VMWare Player)

## Actual behavior
PyTest periodically hangs instead of running/debugging unit tests. In the case of debugging, rather than the status bar at the bottom of the screen turning orange, it remains blue and the "Running Tests" indicator seems to blink forever. Clicking it and selecting the "Stop running tests" command has no effect.

In order to proceed I have to close VS Code and open it again.

Here's a picture of the indicator bar when the bug happens:
image

## Expected  behavior
The tests should run/debug as expected, or at least let me cancel them if they hang.

## Steps to reproduce:  
Hard to say as the problem is intermittent. I notice it most often when I try to debug a specific unit test by pressing the "Debug Test" button above the test definition.  Looking at the console log, the issue maybe be caused by a bug in "Jedi" (not sure what that is).

## Settings  
Your launch.json (if dealing with debugger issues):  
```{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        },
        {
            "name": "Python",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "PySpark",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "osx": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "windows": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit.cmd"
            },
            "linux": {
                "pythonPath": "${env:SPARK_HOME}/bin/spark-submit"
            },
            "program": "${file}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Python Module",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "module": "module.name",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Integrated Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "integratedTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "External Terminal/Console",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${file}",
            "cwd": "",
            "console": "externalTerminal",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit"
            ]
        },
        {
            "name": "Django",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/manage.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "runserver",
                "--noreload"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "DjangoDebugging"
            ]
        },
        {
            "name": "Flask",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "fully qualified path fo 'flask' executable. Generally located along with python interpreter",
            "cwd": "${workspaceRoot}",
            "env": {
                "FLASK_APP": "${workspaceRoot}/quickstart/app.py"
            },
            "args": [
                "run",
                "--no-debugger",
                "--no-reload"
            ],
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Flask (old)",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/run.py",
            "cwd": "${workspaceRoot}",
            "args": [],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Pyramid",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "cwd": "${workspaceRoot}",
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "args": [
                "${workspaceRoot}/development.ini"
            ],
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput",
                "Pyramid"
            ]
        },
        {
            "name": "Watson",
            "type": "python",
            "request": "launch",
            "stopOnEntry": true,
            "pythonPath": "${config:python.pythonPath}",
            "program": "${workspaceRoot}/console.py",
            "cwd": "${workspaceRoot}",
            "args": [
                "dev",
                "runserver",
                "--noreload=True"
            ],
            "env": {},
            "envFile": "${workspaceRoot}/.env",
            "debugOptions": [
                "WaitOnAbnormalExit",
                "WaitOnNormalExit",
                "RedirectOutput"
            ]
        },
        {
            "name": "Attach (Remote Debug)",
            "type": "python",
            "request": "attach",
            "localRoot": "${workspaceRoot}",
            "remoteRoot": "${workspaceRoot}",
            "port": 3000,
            "secret": "my_secret",
            "host": "localhost"
        }
    ]
}
```   
Your settings.json:   
```{
    "python.unitTest.pyTestArgs": [
        "Tests"
    ],
    "python.unitTest.pyTestEnabled": true
}
```   
## Logs
Output from ```Python``` output panel  
None

Output from ```Console window``` (Help->Developer Tools menu)
```extensionHost.ts:293 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 588, in watch
    self._process_request(rq)
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview/jedi/api/__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview/jedi/api/completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "preview/jedi/api/helpers.py", line 153, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.


d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 588, in watch
    self._process_request(rq)
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview/jedi/api/__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview/jedi/api/completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "preview/jedi/api/helpers.py", line 153, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.


d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] ---------------------------
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] stderr jediProxy
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] Error (stderr) Traceback (most recent call last):
  File "completion.py", line 588, in watch
    self._process_request(rq)
  File "completion.py", line 573, in _process_request
    request.get('prefix', '')))
  File "completion.py", line 196, in _serialize_completions
    completions = script.completions()
  File "preview/jedi/api/__init__.py", line 173, in completions
    completions = completion.completions()
  File "preview/jedi/api/completion.py", line 90, in completions
    completion_names = self._get_context_completions()
  File "preview/jedi/api/completion.py", line 118, in _get_context_completions
    grammar, self._code_lines, self._module, self._position
  File "preview/jedi/api/helpers.py", line 153, in get_stack_at_position
    raise SystemError("This really shouldn't happen. There's a bug in Jedi.")
SystemError: This really shouldn't happen. There's a bug in Jedi.


d.logExtensionHostMessage @ extensionHost.ts:293
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
index.js:41 [uncaught exception]: Error: read ECONNRESET
onError @ index.js:41
index.js:44 Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
onError @ index.js:44
events.js:160 Uncaught Error: read ECONNRESET
    at exports._errnoException (util.js:1022)
    at Pipe.onread (net.js:572)
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] TextEditor disposed
d.logExtensionHostMessage @ extensionHost.ts:293
```

### PR DESCRIPTION
**Pull request by DonJayamanne**
fix #1041 when debugging a test do not cancel it when re-discovering tests
Details of the issue can be found here https://github.com/DonJayamanne/pythonVSCode/issues/1041#issuecomment-340261321

A separate PR will be created to fix in multiroot branch (created this PR so that a PR can be tracked as fixing this issue, as squashing commits in multiroot branch will lose all of this history).

### CODE REVIEW

File: src/client/unittests/common/baseTestManager.ts [hunk 1]
```diff
@@ -144,14 +171,15 @@ export abstract class BaseTestManager {
...
         this._status = TestStatus.Running;
-        this.createCancellationToken();
+        this.stop();
+        this.createCancellationToken(CancellationTokenType.testDicovery);
         // If running failed tests, then don't clear the previously build UnitTests
         // If we do so, then we end up re-discovering the unit tests and clearing previously cached list of failed tests
         // Similarly, if running a specific test or test file, don't clear the cache (possible tests have some state information retained)
         const clearDiscoveredTestCache = runFailedTests || moreInfo.Run_Specific_File || moreInfo.Run_Specific_Class || moreInfo.Run_Specific_Function ? false : true;
-        return this.discoverTests(clearDiscoveredTestCache, true)
+        return this.discoverTests(clearDiscoveredTestCache, true, true)
```
Comment (brettcannon) [inline src/client/unittests/common/baseTestManager.ts]: Geez do I miss keyword arguments.

Comment (DonJayamanne) [reply src/client/unittests/common/baseTestManager.ts]: Agreed, the plan is to remove all of these arguments and go with an object (easier).
In some places I got rid of them and added enums (slightly better, improves readability).
E.g. some of the functions have a number of arguments (specially the new changes, but with DI this will hopefully change to a single service provider interface)
