### PR TITLE
Fix #1284 debugging parameterized tests

### LINKED ISSUE #1284: "Debug Test (Multiple)" does not work
## Environment data
VS Code version:  1.17.0
Python Extension version:  0.7.0
Python Version:   3.6
OS and version:    Linux 4.12.13

I have a parametrized `pytest` function and breakpoint inside it. Above the function there is a "button" `Debug Test (Multiple)"

## Actual behavior
When I press `Debug Test (Multiple)`, I'm asked to select a test case, then the test is performed

## Expected  behavior
When I press `Debug Test (Multiple)`, I'm asked to select a test case, then the debug session begins

## Steps to reproduce:  
- 
```
@pytest.mark.parametrize("param", [
    "param0",
    "param1",
    "param2",
])
def test_something(param: str):
    assert param  # set brealpoint here
```
-  run `Debug Test (Multiple)` (link above the function)

### PR DESCRIPTION
**Pull request by DonJayamanne**
Looks I had never tested debugging unit tests with parameterized methods (the code never supported this for parameterized tests)

### CODE REVIEW

File: src/client/unittests/display/picker.ts [hunk 1]
```diff
@@ -55,7 +55,7 @@ export class TestDisplay {
                 testFunctions.some(testFunc => testFunc.nameToRun === fn.testFunction.nameToRun);
         });
 
-        window.showQuickPick(buildItemsForFunctions(rootDirectory, flattenedFunctions),
+        window.showQuickPick(buildItemsForFunctions(rootDirectory, flattenedFunctions, undefined, undefined, debug),
```
Comment (brettcannon) [inline src/client/unittests/display/picker.ts]: It is worth providing default parameters for `buildItemsForFunctions()`?

Comment (DonJayamanne) [reply src/client/unittests/display/picker.ts]: The ```buildItemsForFunctions``` already has default values defined for the parameters. I.e. passing ```undefined``` will result in the those parameters defaulting to their default values.

https://github.com/DonJayamanne/pythonVSCode/pull/1299/files/1d0fdcb401c0476e7f9181bd7d57c4aeb257d557#diff-e4c557dad6f86448a80a2c1a7b2fa045R134
