### PR TITLE
fix #1315 unit tests need to wait for extension to activate

### LINKED ISSUE #1315: Unit tests need to wait for the extension to activate
When running unit tests, the test runner needs to wait for activation to activate.
This causes the unit tests to fail (basically its a timing issue).
Been working all this time, but decided to fail this morning.

### PR DESCRIPTION
**Pull request by DonJayamanne**
This causes the unit tests to fail (basically its a timing issue).
Been working all this time, but decided to fail this morning.

### CODE REVIEW

**Comment by DonJayamanne** [comment]
@brettcannon , the Unit tests have passed for P2.7 (the fixes for unit tests in P3.0 are in the Multiroot branch, its to do with Travis not initializing the Python 3 in the current path)

File: src/client/extension.ts [hunk 1]
```diff
@@ -153,6 +156,7 @@ export async function activate(context: vscode.ExtensionContext) {
     context.subscriptions.push(hepProvider);
 
     context.subscriptions.push(vscode.debug.registerDebugConfigurationProvider('python', new SimpleConfigurationProvider()));
+    activationDeferred.resolve();
```
Comment (brettcannon) [inline src/client/extension.ts]: Is there any reason why it would be better to have `activated` set to `false` and then flip it to `true` here after the activation as resolved? I guess that loss of `const`ness would be unfortunate (basically I'm just trying to learn better TS design 😃 ).

Comment (DonJayamanne) [reply src/client/extension.ts]: It needs to be a promise that can be used from within the unit test. Having a boolean doesn't allow me to **await** on the completion of the above code
